/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Printers */
        get: operations["list_printers_api_printers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Printer */
        get: operations["get_printer_api_printers__printer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Printer Detail
         * @description Full per-printer view (modeled state + identity + complete raw report).
         */
        get: operations["get_printer_detail_api_printers__printer_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}/job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Job
         * @description Upload a sliced 3MF and arm the swap plan.
         *
         *     ``start=true`` (default) also pushes (FTPS) + starts the print — the still-unverified
         *     v0.4 path. ``start=false`` ARMS ONLY: the operator starts the print themselves (Bambu
         *     Studio / SD) and the Brain owns the swap loop from the pause onward (no FTPS needed).
         */
        post: operations["submit_job_api_printers__printer_id__job_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}/job/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Armed Job
         * @description Push (FTPS) + start the job this printer is ALREADY armed with.
         *
         *     The two-step flow: upload with ``?start=false`` to arm + propose the mapping, let the
         *     operator confirm it (POST ``/job/assignment``), then call this to start the held job
         *     WITHOUT re-arming (which would wipe the confirmed assignment). 409 if nothing is armed.
         */
        post: operations["start_armed_job_api_printers__printer_id__job_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Prompts
         * @description Pending human-swap actions the orchestrator is waiting on.
         */
        get: operations["list_prompts_api_prompts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/{prompt_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Prompt */
        post: operations["answer_prompt_api_prompts__prompt_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}/orchestrator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Orchestrator
         * @description The armed swap loop for this printer (cursor / held / swap_state / alerts).
         *
         *     404 if the printer is unknown; ``{"armed": false}`` if no job has been submitted yet.
         */
        get: operations["get_orchestrator_api_printers__printer_id__orchestrator_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Modules
         * @description All configured AMS modules (for the add-spool form module dropdown).
         */
        get: operations["list_modules_api_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Spools
         * @description List all spools from the inventory (Spoolman or fake).
         */
        get: operations["list_spools_api_spools_get"];
        put?: never;
        /**
         * Create Spool
         * @description Create a new spool in the inventory.
         */
        post: operations["create_spool_api_spools_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spools/{spool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Spool
         * @description Hard-delete a spool from the inventory.
         */
        delete: operations["delete_spool_api_spools__spool_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Spool
         * @description Update weight, location, or archived status of a spool.
         */
        patch: operations["update_spool_api_spools__spool_id__patch"];
        trace?: never;
    };
    "/api/printers/{printer_id}/loadout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Loadout
         * @description Current spool→module mapping for every configured module on this printer.
         */
        get: operations["get_loadout_api_printers__printer_id__loadout_get"];
        /**
         * Set Loadout
         * @description Assign a spool to a module (writes `set_module` on the store).
         */
        put: operations["set_loadout_api_printers__printer_id__loadout_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}/job/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assignment
         * @description Current spool-assignment proposal for the armed job on this printer.
         *
         *     Returns rows (one per filament index from the plan), each with the module/spool the
         *     resolver proposed. `confirmed` is True once the operator has POST-confirmed the mapping.
         *     Returns empty rows + confirmed=False when no job is armed.
         */
        get: operations["get_assignment_api_printers__printer_id__job_assignment_get"];
        put?: never;
        /**
         * Confirm Assignment
         * @description Confirm (and optionally override) the index→module mapping.
         *
         *     Body: `{index: module_id}` for each filament index. Persists each override into
         *     brain.assignment so a follow-up GET reflects the chosen module/status. For rows
         *     that carry a spool_id, also calls set_module on the store (SOFT — store errors are
         *     logged and skipped so Spoolman down never 500s this endpoint).
         *     Returns `{ok: true}`.
         */
        post: operations["confirm_assignment_api_printers__printer_id__job_assignment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}/sim/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sim Pause
         * @description Inject a filament-change pause (simulate mode only).
         *
         *     Default (no params): an UNTAGGED pause carrying the next expected swap's gcode ``line`` —
         *     exactly what a real Bambu ``M400 U1`` looks like, so it exercises the #17 ordinal+line
         *     guard the real loop uses. Pass ``?line=`` to force a different line (e.g. a far value to
         *     hit the safe-hold path), or ``?tag=`` to inject a tagged pause (and force a tag mismatch).
         *     Returns immediately; the swap then blocks on the human prompt — poll ``/api/prompts``.
         */
        post: operations["sim_pause_api_printers__printer_id__sim_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/printers/{printer_id}/sim/sensor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sim Sensor
         * @description Trip (or clear) the printer's filament-present sensor (simulate mode only).
         *
         *     Publishes a ``SensorEvent`` — the signal that closes the orchestrator's SENSING loop.
         *     Call this once the swap has reached SENSING (after answering the feed prompt).
         */
        post: operations["sim_sensor_api_printers__printer_id__sim_sensor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerResult
         * @description POST /api/prompts/{prompt_id}/answer.
         */
        AnswerResult: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Prompt Id */
            prompt_id: string;
        };
        /**
         * AssignRow
         * @description One filament index from the armed plan with the module/spool the resolver proposed.
         */
        AssignRow: {
            /** Index */
            index: number;
            /** Material */
            material: string | null;
            /** Color Hex */
            color_hex: string | null;
            /** Grams */
            grams: number | null;
            /** Module */
            module: string | null;
            /** Spool Id */
            spool_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "loaded" | "gap";
        };
        /**
         * AssignmentResponse
         * @description GET /api/printers/{id}/job/assignment. ``rows`` is empty when nothing is armed.
         */
        AssignmentResponse: {
            /** Rows */
            rows: components["schemas"]["AssignRow"][];
            /** Confirmed */
            confirmed: boolean;
        };
        /** Body_submit_job_api_printers__printer_id__job_post */
        Body_submit_job_api_printers__printer_id__job_post: {
            /** File */
            file: string;
        };
        /**
         * DeleteResult
         * @description DELETE /api/spools/{spool_id}.
         */
        DeleteResult: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Id */
            id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description GET /health.
         */
        Health: {
            /** Ok */
            ok: boolean;
            /** Simulate */
            simulate: boolean;
            /** Printers */
            printers: string[];
            /** Modules */
            modules: number;
        };
        /**
         * JobResult
         * @description POST /api/printers/{id}/job.
         */
        JobResult: {
            /** Printer Id */
            printer_id: string;
            /** Filename */
            filename: string | null;
            /** Started */
            started: boolean;
            /** Planned Swaps */
            planned_swaps: components["schemas"]["PlannedSwap"][];
        };
        /**
         * LoadedFilament
         * @description What the Brain believes is loaded — Pi-authoritative, never set from a report.
         */
        LoadedFilament: {
            /** Index */
            index: number;
            /** Material */
            material: string | null;
            /** Color */
            color: string | null;
        };
        /**
         * LoadoutRow
         * @description One configured module and the spool currently loaded in it (null when empty).
         */
        LoadoutRow: {
            /** Module */
            module: string;
            spool: components["schemas"]["Spool"] | null;
        };
        /**
         * ModuleInfo
         * @description One configured AMS module. ``filament_index`` is null when the slot is unmapped.
         */
        ModuleInfo: {
            /** Id */
            id: string;
            /** Cluster Id */
            cluster_id: string;
            /** Filament Index */
            filament_index: number | null;
        };
        /**
         * OkResponse
         * @description Bare success ack (PUT /loadout, POST /job/assignment).
         */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /**
         * OrchestratorArmed
         * @description The live swap loop for a printer with a job armed.
         */
        OrchestratorArmed: {
            /**
             * Armed
             * @default true
             * @constant
             */
            armed: true;
            /** Printer Id */
            printer_id: string;
            /** Cursor */
            cursor: number;
            /** Total */
            total: number;
            /** Done */
            done: boolean;
            /** Held */
            held: boolean;
            /** Swap State */
            swap_state: string;
            /** Alerts */
            alerts: string[];
            /** Swaps */
            swaps: components["schemas"]["OrchestratorSwap"][];
        };
        /**
         * OrchestratorIdle
         * @description No job armed for this printer yet.
         */
        OrchestratorIdle: {
            /**
             * Armed
             * @default false
             * @constant
             */
            armed: false;
            /** Printer Id */
            printer_id: string;
        };
        /**
         * OrchestratorSwap
         * @description One swap in the armed plan, flagged when it is the cursor's current target.
         */
        OrchestratorSwap: {
            /** Seq */
            seq: number;
            /** Filament Index */
            filament_index: number;
            /** Tag */
            tag: string;
            /** Current */
            current: boolean;
        };
        /**
         * PlannedSwap
         * @description One planned material change, as echoed back on upload.
         */
        PlannedSwap: {
            /** Seq */
            seq: number;
            /** Filament Index */
            filament_index: number;
            /** Tag */
            tag: string;
        };
        /**
         * PrinterDetail
         * @description GET /api/printers/{id}/detail — modeled state + identity + the full raw report.
         *
         *     ``raw`` is the deep-merged snapshot of the printer's own report (temps, fans, wifi, ams,
         *     ipcam, ...). It is printer- and firmware-dependent, so it stays open JSON and is rendered
         *     generically by the UI. The access code is never included.
         */
        PrinterDetail: {
            /** Id */
            id: string;
            /** Stage */
            stage: string;
            /** Pause Reason */
            pause_reason: string | null;
            /** Filament Sensor */
            filament_sensor: boolean;
            progress: components["schemas"]["Progress"];
            loaded_filament: components["schemas"]["LoadedFilament"] | null;
            /** Serial */
            serial: string;
            /** Model */
            model: string;
            /** Ip */
            ip: string | null;
            /** Simulate */
            simulate: boolean;
            /** Connected */
            connected: boolean;
            /** Seeded */
            seeded: boolean;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
        };
        /**
         * PrinterState
         * @description GET /api/printers and GET /api/printers/{id} — the modeled printer snapshot.
         */
        PrinterState: {
            /** Id */
            id: string;
            /** Stage */
            stage: string;
            /** Pause Reason */
            pause_reason: string | null;
            /** Filament Sensor */
            filament_sensor: boolean;
            progress: components["schemas"]["Progress"];
            loaded_filament: components["schemas"]["LoadedFilament"] | null;
        };
        /**
         * Progress
         * @description Best-effort progress from the printer report.
         *
         *     The server only ever writes ``layer`` / ``percent`` / ``line`` (see
         *     ``Printer._apply_fields``), and it already treats a non-int layer/line as absent.
         *     ``extra="allow"`` keeps any future report key from being silently dropped on the way out.
         */
        Progress: {
            /** Layer */
            layer?: number | null;
            /** Percent */
            percent?: number | null;
            /** Line */
            line?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Prompt
         * @description One pending human-swap action the orchestrator is blocked on.
         */
        Prompt: {
            /** Id */
            id: string;
            /** Module Id */
            module_id: string;
            /** Message */
            message: string;
        };
        /**
         * SimPauseResult
         * @description POST /api/printers/{id}/sim/pause — echoes which form of pause was injected.
         */
        SimPauseResult: {
            /**
             * Injected
             * @default pause
             * @constant
             */
            injected: "pause";
            /** Printer Id */
            printer_id: string;
            /** Tag */
            tag?: string | null;
            /** Line */
            line?: number | null;
        };
        /**
         * SimSensorResult
         * @description POST /api/printers/{id}/sim/sensor.
         */
        SimSensorResult: {
            /**
             * Injected
             * @default sensor
             * @constant
             */
            injected: "sensor";
            /** Printer Id */
            printer_id: string;
            /** Filament Present */
            filament_present: boolean;
        };
        /**
         * Spool
         * @description One physical spool from the inventory. ``color_hex`` is bare 6-hex RRGGBB (no '#').
         */
        Spool: {
            /** Id */
            id: string;
            /** Filament Id */
            filament_id: string;
            /** Material */
            material: string | null;
            /** Color Hex */
            color_hex: string | null;
            /** Name */
            name: string | null;
            /** Remaining G */
            remaining_g: number | null;
            /** Module */
            module: string | null;
            /** Archived */
            archived: boolean;
        };
        /**
         * SpoolCreate
         * @description Request body for POST /api/spools.
         */
        SpoolCreate: {
            /** Material */
            material: string;
            /** Color Hex */
            color_hex?: string | null;
            /** Name */
            name?: string | null;
            /** Vendor */
            vendor?: string | null;
            /**
             * Initial G
             * @default 1000
             */
            initial_g: number;
            /** Module */
            module?: string | null;
            /** Location */
            location?: string | null;
        };
        /**
         * SpoolUpdate
         * @description Request body for PATCH /api/spools/{spool_id}.
         */
        SpoolUpdate: {
            /** Remaining G */
            remaining_g?: number | null;
            /** Location */
            location?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /**
         * StartArmedResult
         * @description POST /api/printers/{id}/job/start.
         */
        StartArmedResult: {
            /** Printer Id */
            printer_id: string;
            /** Started */
            started: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_printers_api_printers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterState"][];
                };
            };
        };
    };
    get_printer_api_printers__printer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_printer_detail_api_printers__printer_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_api_printers__printer_id__job_post: {
        parameters: {
            query?: {
                start?: boolean;
            };
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_job_api_printers__printer_id__job_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_armed_job_api_printers__printer_id__job_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartArmedResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompts_api_prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"][];
                };
            };
        };
    };
    answer_prompt_api_prompts__prompt_id__answer_post: {
        parameters: {
            query?: {
                response?: string;
            };
            header?: never;
            path: {
                prompt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orchestrator_api_printers__printer_id__orchestrator_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrchestratorArmed"] | components["schemas"]["OrchestratorIdle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_modules_api_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleInfo"][];
                };
            };
        };
    };
    list_spools_api_spools_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Spool"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_spool_api_spools_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpoolCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Spool"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_spool_api_spools__spool_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_spool_api_spools__spool_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spool_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpoolUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Spool"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loadout_api_printers__printer_id__loadout_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadoutRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_loadout_api_printers__printer_id__loadout_put: {
        parameters: {
            query: {
                module: string;
                spool_id: string;
            };
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assignment_api_printers__printer_id__job_assignment_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_assignment_api_printers__printer_id__job_assignment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sim_pause_api_printers__printer_id__sim_pause_post: {
        parameters: {
            query?: {
                tag?: string | null;
                line?: number | null;
            };
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimPauseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sim_sensor_api_printers__printer_id__sim_sensor_post: {
        parameters: {
            query?: {
                present?: boolean;
            };
            header?: never;
            path: {
                printer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimSensorResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
